let catalogo=[
    {"id": 1, "nombre": "Pañalero Banda", "tipo": "pañalero", "cantidad": 1, "desc": "Pañalero y bandita de bebe, color a elegir", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665523145/Tienda/accesorios/pa%C3%B1aleroBanda_x4eiyt.jpg"},
    {"id": 2, "nombre": "Cinturon Baby2", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon de maternidad para Baby Shower, color a elegir", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665522673/Tienda/accesorios/cinturonBaby2_bqcdav.jpg"},
    {"id": 3, "nombre": "Cinturon Banda", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon de maternidad y Banda de bebe, color a elegir", "precio": 1000, "img":  " https://res.cloudinary.com/djgf7eniw/image/upload/v1665522757/Tienda/accesorios/cinturonBanda_fz2xdw.jpg"},
    {"id": 4, "nombre": "Moño 1", "tipo": "moño", "cantidad": 1, "desc": "Moño color blanco de niña, para cualquier evento especial", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665522731/Tienda/accesorios/mo%C3%B1o1_fvhst0.jpg"},
    {"id": 5, "nombre": "Combo1", "tipo": "banda", "cantidad": 1, "desc": "Cinturon de niña,tocado para peinado y moño de niño, color a elegir", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665523247/Tienda/accesorios/combo1_fehrl9.jpg"},
    {"id": 6, "nombre": "Combo2", "tipo": "banda", "cantidad": 1, "desc": "Cinturon de maternidad,moño de niña y banda de bebe, color a elegir", "precio": 1000, "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665522833/Tienda/accesorios/combo2_xosslt.jpg" },
    {"id": 7, "nombre": "Cinturon Dama(xv)", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon para las Damas de la Quinceñera o para damas de honor de Novia", "precio": 150, "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665522750/Tienda/accesorios/cinturonDama_xv_hostqu.jpg"},
    {"id": 8, "nombre": "Moño Hombre(xv)", "tipo": "moño", "cantidad": 1, "desc": "Moños para Chambelanes de Quinceñera, color a elegir", "precio": 1000, "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665522816/Tienda/accesorios/mo%C3%B1oHombre_xv_jx7prr.jpg"},
    {"id": 9, "nombre": "Pulsera Dama(xv o boda)", "tipo": "pulsera", "cantidad": 1, "desc": "Pulsera para Damas de honor, color a elegir", "precio": 1000,"img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665523116/Tienda/accesorios/pulseraDama_xv-boda_ocdvef.jpg"},
    {"id": 10, "nombre": "Pies Descalzos", "tipo": "banda", "cantidad": 1, "desc": "Banda de bebe y pies descalzos en colores disponibles", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665522857/Tienda/accesorios/piesDescalzos_dj6diq.jpg"},
    {"id": 11, "nombre": "Cinturon Baby1", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon de maternidad con distintivo para el pápa, color a elegir", "precio": 1000, "talla": "L", "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665522705/Tienda/accesorios/cinturonBaby1_lfpz4q.jpg"},
    {"id": 12, "nombre": "Moño 2", "tipo": "moño", "cantidad": 1, "desc": "Broche con flores de diferente color a elegir", "precio": 1000, "img":"https://res.cloudinary.com/djgf7eniw/image/upload/v1665524909/Tienda/accesorios/mo%C3%B1o2_pxnr5n.jpg"}, 
    
    
    {"id": 13, "nombre": "Cinturon", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon de maternidad para BabyShower", "precio": 1000, "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665524737/Tienda/accesorios/cinturonBaby4_f39bqp.jpg"},
    {"id": 14, "nombre": "Cinturon", "tipo": "cinturon", "cantidad": 1, "desc": "Cinturon de maternidad para BabyShower", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665524755/Tienda/accesorios/cinturonBaby3_ockayj.jpg"},
    {"id": 15, "nombre": "Moño", "tipo": "moño", "cantidad": 1, "desc": "Moño personalizado para niña", "precio": 1000, "img":" https://res.cloudinary.com/djgf7eniw/image/upload/v1665523097/Tienda/accesorios/mo%C3%B1o5_btebda.jpg"}, 
    {"id": 16, "nombre": "Banda", "tipo": "Banda", "cantidad": 1, "desc": "Banda y pies descalzos para Bautizo", "precio": 1000, "img": " https://res.cloudinary.com/djgf7eniw/image/upload/v1665524784/Tienda/accesorios/bandaBautizo_rggcbu.jpg"}
] 
    
